name: lapt
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - datasets=3.*
  - hydra-core=1.*
  - numpy<2.0
  - sentencepiece=0.*
  - tokenizers=0.*
  - transformers=4.*
  - pip
  - protobuf
  - pyyaml
  - tqdm
  - yapf
  - pip:
    - torch==2.2.*
