type: multinomial
language: old_germanic
sources:
  - type: plaintext
    language: ang
    path: data/beowulf/beowulf_clean.txt
  - type: plaintext
    language: got
    path: data/gotica/gotica_clean.txt
  - type: concat
    language: non
    sources:
      - type: plaintext
        path: data/sagas/sagas_clean.txt
      - type: plaintext
        path: data/icecorpus-texts/icepahc_12th-18th_clean.txt
alpha: 0.7
total_samples: 20000
cache_dir: "data/old_germanic"
