# general
seed: 1
output_dir: models/hy_model

# training
dataset_path: data/hy_oscar
language_code: hy
hf_model: facebook/xglm-564M
dev_size: 0.0025
max_steps: 5000
max_length: 256
train_batch_size: 20
eval_batch_size: 40
